# Generated by Django 4.1.7 on 2026-03-06 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="question", name="correct_answer", field=models.IntegerField(),
        ),
    ]
