# Generated by Django 4.1.7 on 2026-03-07 20:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("exams", "0005_cheatingscreenshot"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cheatingscreenshot",
            name="exam",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cheating_screenshots",
                to="exams.exam",
            ),
        ),
        migrations.AlterField(
            model_name="cheatingscreenshot",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cheating_screenshots",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="correct_answer",
            field=models.IntegerField(help_text="Enter option number (1-4)"),
        ),
    ]
