# Generated by Django 4.1.7 on 2026-04-06 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_alter_cheatingscreenshot_exam_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="end_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="exam",
            name="start_time",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
